### ISSUE TITLE
How to have an application join an existing session

### ISSUE THREAD

**Issue by matthewrobb** [thibauts/node-castv2-client#31] opened 2015-04-20 15:08 UTC
I am writing an application that monitors devices on the network and allows a person to setup default applications etc. One problem I am having is that when you launch an application and then say end the process, the chromecast app session ends.

Right now I have two differrent needs:
1. Monitor devices and make sure each one is casting the right app
2. Listen for commands from another location (http server) and forward them on to a device running the app.

The first one works great for me doing the following:
```javascript
function onConnect(service) {

  var client = new PlatformSender();

  client.connect(service.addresses[0], function() {
    var receiver = client.receiver;
    
    function syncApp(app) {
      if(syncApp.launching || app.appId === syncAppId) return;

      syncApp.launching = true;

      console.log("Restoring %s to default app: %s...", app.name, syncAppId);
      if(app.sessionId) {
        receiver.stop(app.sessionId, function(err, apps) {
          log(apps);
        });
      }

      receiver.launch(syncAppId, function(err, response) {
        syncApp.launching = false;
      });
    }

    client.on("status", function(status) {
      syncApp((status && status.applications && status.applications[0]) || {});
    });

    client.getStatus(function(err, status) {
      if(!err) {
        client.emit("status", status);
      }
    });
  });
}
```
This will launch the app and keep it launched no matter what. If the process that executed the above code were to exit the app stays on the chromecast just fine and if the process then comes back up it recovers just fine and doesn't force the running app to relaunch.

The second need requires me to have established a custom namespaced channel for sending requests to the ALREADY LAUNCHED app. For this I basically cloned the Youtube custom sender project and am using a different namespace.

The problem is that for one, when doing `client.launch(App, cb)` it "closes" the ALREADY LAUNCHED app and re-launches it. The second issue is that if I ONLY use the app then when the process exits it also causes the app the close on the Chromecast:
```javascript
function onConnect(service) {

  var client = new PlatformSender();

  client.connect(service.addresses[0], function() {

    function syncApp(app) {
      if(syncApp.launching || app.appId === syncAppId) {
        return;
      }

      syncApp.launching = true;

      console.log("Restoring %s to default app: %s...", app.name, syncAppId);
      if(app.sessionId) {
        receiver.stop(app.sessionId, function(err, apps) {
          log(apps);
        });
      }
      client.launch(PipecastApp, function(err, pio) {
        log('app launched');

        syncApp.launching = false;

        pio.request(...)
      });
    }

    client.on("status", function(status) {
      syncApp((status && status.applications && status.applications[0]) || {});
    });

    client.getStatus(function(err, status) {
      if(!err) {
        client.emit("status", status);
      }
    });
  });
}
```
Again, the above works so long as I am maintaining the process but as soon as it exits the app on the Chromecast also closes.

I need to figure out a way to either have an app join an existing session in a way that it won't auto close it later or I need to figure out why it's closing in the first place and get it to stop.

Any help would be greatly appreciated, thanks!

**Comment by thibauts** [comment] 2015-04-20 15:16
Looks like an interesting project !

You may be interested in [getSessions](https://github.com/thibauts/node-castv2-client/blob/master/lib/senders/platform.js#L73-L75) and [join](https://github.com/thibauts/node-castv2-client/blob/master/lib/senders/platform.js#L87-L89). `join` takes as a first param one of the sessions returned by `getSessions`, and as a second param the app class (same as `launch`). Let me know if it doesn't make sense.

**Comment by matthewrobb** [comment] 2015-04-20 15:20
I am working on a controller app for digital signage in a business such as a grocery store. The app needs to guaruntee no undesired casts take place (trolls). Also as screens power on/off it needs to be able to get them back to casting a sign.

I actually just solved the problem after posting this, it was a bug in my receiver application. It didn't trigger an event with the first method because of the different namespaces.

**Comment by thibauts** [comment] 2015-04-20 15:29
Cool ! It's always nice to see this module used in real-world apps. If you're confident you have your solution don't hesitate to close the issue.

**Closed** 2015-04-20 15:30 UTC

**Comment by icebergcwp1990** [comment] 2016-11-04 07:14
@matthewrobb Hi,matthewrobb,I am looking for a way to join an existing session,but I have no idea. I wanna ask you about this , Have you solved this issue? I need you help .

**Comment by matthewrobb** [comment] 2016-11-04 13:12
I did get all of this working but I haven't been in the code now for quite a while. Feel free to ask any specific questions and I'll see what I can remember!

**Comment by icebergcwp1990** [comment] 2016-11-07 09:00
Thanks !  I am working on a controller app for casting the media stream catching from a music website ,   and I need to make it in Objective-C language . The problem is I can't google more information about how to control Google Cast Device fully . Demos of google cast in the github help me solve a lots of issue , but I need more info . Do you have any comprehensive documents ? Thanks again.
